jobboard/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path
from users import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
# += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.homeView, name='home'),

    path('signup/', views.SignupView.as_view(), name='applicant_register'),
    path('login/', views.LoginView.as_view(), name='applicant_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('job/add', views.post_job, name='job_post'),
    #path('employer_login/', views.EmployerLoginView.as_view(), name='employer_login'),
    path('logout/', views.sign_out, name='logout'),
    path('job_list/', views.job_list, name='joblist'),

    path('search/', views.job_search, name='job_search'),

    path('job/<int:job_id>/details', views.job_details, name='job_details'),
    path('job/<int:job_id>/apply', views.job_apply, name='apply'),
    path('my_applications/', views.my_applied_jobs, name='my_applications'),

    path('employer/job_list/', views.employer_job_list, name='employer_job_list'),
    path('employer/job_list/edit/<int:job_id>', views.edit_job, name='edit_job'),

    path('job_applications/<int:job_id>/', views.view_job_applications, name='job_applications'),
    path('job_applications/detail/<int:application_id>/', views.application_detail_view, name='application_detail'),
  
]

templates/new/add_job_form.html
{% extends 'new/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section class="section-hero overlay inner-page bg-image" id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold">Add new Job</h1>
          <div class="custom-breadcrumbs">
            <a href="{% url 'users:home' %}">Home</a> <span class="mx-2 slash">/</span>
            <span class="text-white"><strong>Add job</strong></span>
          </div>
        </div>
      </div>
    </div>
</section>

<section class="site-section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col">
          <h2 class="mb-4">Add new job form</h2>
          <script src="//cdn.ckeditor.com/4.21.0/standard/ckeditor.js"></script>
          
          <form action="#" method="post" class="p-4 border rounded" enctype='multipart/form-data'>
            {% csrf_token %}
            {{form.media}}
            {{ form.as_p }}
            
            <!--
            <div class="row form-group">
              <div class="col-md-12 mb-3 mb-md-0">
                <label class="text-black" for="fname">Email</label>
                <input type="text" id="fname" class="form-control" placeholder="Email address">
              </div>
            </div>
            <div class="row form-group mb-4">
              <div class="col-md-12 mb-3 mb-md-0">
                <label class="text-black" for="fname">Password</label>
                <input type="password" id="fname" class="form-control" placeholder="Password">
              </div>
            </div>
            -->
            <div class="row form-group justify-content-center mt-5">
              <div class="col-md-12 text-center">
                <input type="submit" value="Create Job" class="btn  btn-primary btn-block text-white">
              </div>
            </div>
            
          </form>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/new/employer_jobs.html
{% extends 'new/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section class="section-hero overlay inner-page bg-image" id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold">Your Job Listings</h1>
          <div class="custom-breadcrumbs">
            <a href="{% url 'users:home' %}">Home</a> <span class="mx-2 slash">/</span>
            <span class="text-white"><strong>My Jobs</strong></span>
          </div>
        </div>
      </div>
    </div>
</section>

<section class="site-section">
    <div class="container">
  
      <div class="row mb-5 justify-content-center">
        <div class="col-md-7 text-center">
          <h2 class="section-title mb-2">Job Listed</h2>
        </div>
      </div>
      
      {% if jobs %}
        <ul class="job-listings mb-5">
         
          {% for job in jobs %}
          
          <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
            
            <a href="{% url 'users:edit_job' job_id=job.id %}"></a>
            <div class="job-listing-logo">
              <img src="{{job.featured_image.url}}" alt="Free Website Template by Free-Template.co" class="img-fluid">
            </div>
  
            <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
              
              <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
                <h2>{{job.job_title}}</h2>
                <strong>{{ job.company_name }}</strong>
                <span class="icon-room"></span> {{ job.location }}
                <span class="badge badge-danger"> {{ job.job_type }}</span>
              </div>
              
              <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
                <a href="{% url 'users:job_applications' job_id=job.id %}" type='button' class="btn btn-primary text-white" style="height: auto; width:auto">View Applicants</a>
              </div>
            </div>
            
      
          </li> 
          {% endfor %} 
        </ul>
  
      {% else %}
        <h2>No jobs found!</h2>
      {% endif %}
  
      
  
    </div>
  </section>
{% endblock %}

templates/new/footer.html
{% load static %}

<footer class="site-footer">

    <a href="#top" class="smoothscroll scroll-top">
      <span class="icon-keyboard_arrow_up"></span>
    </a>

    <div class="container">
      <div class="row mb-5">
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <h3>Search Trending</h3>
          <ul class="list-unstyled">
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Graphic Design</a></li>
            <li><a href="#">Web Developers</a></li>
            <li><a href="#">Python</a></li>
            <li><a href="#">HTML5</a></li>
            <li><a href="#">CSS3</a></li>
          </ul>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <h3>Company</h3>
          <ul class="list-unstyled">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Career</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Resources</a></li>
          </ul>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <h3>Support</h3>
          <ul class="list-unstyled">
            <li><a href="#">Support</a></li>
            <li><a href="#">Privacy</a></li>
            <li><a href="#">Terms of Service</a></li>
          </ul>
        </div>
        <div class="col-6 col-md-3 mb-4 mb-md-0">
          <h3>Contact Us</h3>
          <div class="footer-social">
            <a href="#"><span class="icon-facebook"></span></a>
            <a href="#"><span class="icon-twitter"></span></a>
            <a href="#"><span class="icon-instagram"></span></a>
            <a href="#"><span class="icon-linkedin"></span></a>
          </div>
        </div>
      </div>

      <div class="row text-center">
        <div class="col-12">
          <p class="copyright"><small>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></small></p>
        </div>
      </div>
    </div>
  </footer>

templates/new/index.html
{% extends 'new/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<!-- HOME -->
<section class="home-section section-hero overlay bg-image" id="home-section">

  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-12">
        <div class="mb-5 text-center">
          <h1 class="text-white font-weight-bold">The Easiest Way To Get Your Dream Job</h1>
          <p>Take your career to next level here.</p>
        </div>
        <form method="GET" class="search-jobs-form" action="{% url 'users:job_search' %}">
          {% csrf_token %}
          <div class="row mb-5">
            <div class="col">
              <input type="text" id="seach-input" class="form-control form-control-lg" name="q"
                placeholder="Job title, Company...">
            </div>

            <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
              <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span
                  class="icon-search icon mr-2"></span>Search Job</button>
            </div>
          </div>

        </form>
      </div>
    </div>
  </div>

  <a href="#next" class="scroll-button smoothscroll">
    <span class=" icon-keyboard_arrow_down"></span>
  </a>

</section>


<section class="site-section">
  <div class="container">

    <div class="row mb-5 justify-content-center">
      <div class="col-md-7 text-center">
        <h2 class="section-title mb-2">Latest Jobs</h2>
      </div>
    </div>

    {% if jobs %}
    <ul class="job-listings mb-5">

      {% for job in jobs %}

      <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">

        <a href="{% url 'users:job_details' job_id=job.id %}"></a>
        <div class="job-listing-logo">
          <img src="{{job.logo.url}}" alt="Free Website Template by Free-Template.co" class="img-fluid">
        </div>

        <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
          <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
            <h2>{{job.job_title}}</h2>
            <strong>{{ job.company_name }}</strong>
          </div>
          <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
            <span class="icon-room"></span> {{ job.location }}

          </div>
          <div class="job-listing-meta">
            <span class="badge badge-danger">{{ job.job_type }}</span>
          </div>
        </div>

      </li>
      {% endfor %}
    </ul>

    {% else %}
    <h2>No jobs found!</h2>
    {% endif %}

    

  </div>
</section>

{% endblock %}

templates/new/job_detail.html
{% extends 'new/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section class="section-hero overlay inner-page bg-image" id="home-section">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1 class="text-white font-weight-bold">Job detail</h1>
                <div class="custom-breadcrumbs">
                    <a href="{% url 'users:home' %}">Home</a> <span class="mx-2 slash">/</span>
                    <span class="text-white"><strong>Job detail</strong></span>
                </div>
            </div>
        </div>
    </div>
</section>


  
  <section class="site-section">
    <div class="container">
      <div class="row align-items-center mb-5">
        <div class="col-lg-8 mb-4 mb-lg-0">
          <div class="d-flex align-items-center">
            <div class="border p-2 d-inline-block mr-3 rounded">
              <img src="{{job.featured_image.url}}" alt="Image">
            </div>
            <div>
              <h2>{{job.job_title}}</h2>
              <div>
                <span class="ml-0 mr-2 mb-2"><span class="icon-briefcase mr-2"></span>{{job.company_name}}</span>
                <span class="m-2"><span class="icon-room mr-2"></span>{{job.location}}</span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="row">
            
            <div class="col-6">
              <a href="{% url 'users:apply' job_id=job.id %}" class="btn btn-block btn-primary btn-md">Apply Now</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-8">
          <div class="mb-5">
            <figure class="mb-5"><img src="{{job.logo.url}}" alt="Image" class="img-fluid rounded"></figure>
            <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-align-left mr-3"></span>Job Description</h3>
            <p>{{job.job_description|safe}}</p>
            
          </div>
         

          <div class="mb-5">
            <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-turned_in mr-3"></span>About {{job.company_name}}</h3>
            <p>{{job.company_description|safe}}</p>
          </div>

          <div class="row mb-5">
            <div class="col-6">
              <a href="{% url 'users:apply' job_id=job.id %}" class="btn btn-block btn-primary btn-md">Apply Now</a>
            </div>
          </div>

        </div>
        <div class="col-lg-4">
          <div class="bg-light p-3 border rounded mb-4">
            <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Job Summary</h3>
            <ul class="list-unstyled pl-3 mb-0">
              <li class="mb-2"><strong class="text-black">Published on:</strong> {{job.created_at}}</li>
              <li class="mb-2"><strong class="text-black">Industry:</strong> {{job.job_type}}</li>
              <li class="mb-2"><strong class="text-black">Experience:</strong> {{job.experience_min}} to {{job.experience_max}} year(s)</li>
              <li class="mb-2"><strong class="text-black">Job Location:</strong> {{job.location}}</li>
              <li class="mb-2"><strong class="text-black">Salary:</strong> {{job.salary_min}} - {{job.salary_max}}</li>
              <li class="mb-2"><strong class="text-black">Application Deadline:</strong> {{job.last_date_of_application}}</li>
            </ul>
          </div>

         

        </div>
      </div>
    </div>
  </section>


{% endblock %}

templates/new/job_search.html
{% extends 'new/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section class="section-hero overlay inner-page bg-image" id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold">Seach result for {{query}}</h1>
          <div class="custom-breadcrumbs">
            <a href="{% url 'users:home' %}">Home</a> <span class="mx-2 slash">/</span>
            <span class="text-white"><strong>Search</strong></span>
          </div>
        </div>
      </div>
    </div>
</section>

<section class="site-section">
    <div class="container">
  
      <div class="row mb-5 justify-content-center">
        <div class="col-md-7 text-center">
          <h2 class="section-title mb-2">Jobs Matching {{query}}</h2>
        </div>
      </div>
      
      {% if jobs %}
        <ul class="job-listings mb-5">
         
          {% for job in jobs %}
          
          <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
            
            <a href="{% url 'users:job_details' job_id=job.id %}"></a>
            <div class="job-listing-logo">
              <img src="{{job.logo.url}}" alt="Free Website Template by Free-Template.co" class="img-fluid">
            </div>
  
            <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
              <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
                <h2>{{job.job_title}}</h2>
                <strong>{{ job.company_name }}</strong>
              </div>
              <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
                <span class="icon-room"></span> {{ job.location }}
                
              </div>
              <div class="job-listing-meta">
                <span class="badge badge-danger">{{ job.job_type }}</span>
              </div>
            </div>
      
          </li> 
          {% endfor %} 
        </ul>
  
      {% else %}
        <h2>No jobs found!</h2>
      {% endif %}
  
    </div>
  </section>
{% endblock %}

templates/new/login.html
{% extends 'new/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section class="section-hero overlay inner-page bg-image" id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold">Login</h1>
          <div class="custom-breadcrumbs">
            <a href="{% url 'users:home' %}">Home</a> <span class="mx-2 slash">/</span>
            <span class="text-white"><strong>Log In</strong></span>
          </div>
        </div>
      </div>
    </div>
</section>

<section class="site-section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6">
          <h2 class="mb-4">Log In To JobBoard</h2>
          
          <form action="#" method="post" class="p-4 border rounded">
            {% csrf_token %}
            {{ form.as_p }}
            
            <!--
            <div class="row form-group">
              <div class="col-md-12 mb-3 mb-md-0">
                <label class="text-black" for="fname">Email</label>
                <input type="text" id="fname" class="form-control" placeholder="Email address">
              </div>
            </div>
            <div class="row form-group mb-4">
              <div class="col-md-12 mb-3 mb-md-0">
                <label class="text-black" for="fname">Password</label>
                <input type="password" id="fname" class="form-control" placeholder="Password">
              </div>
            </div>
            -->
            <div class="row form-group justify-content-center mt-5">
              <div class="col-md-12 text-center">
                <input type="submit" value="Log In" class="btn  btn-primary btn-block text-white">
              </div>
              <div class="text-center mt-4">
                <p>Not a member? <a href="{% url 'users:applicant_register' %}">Register</a></p>
              </div>
            </div>
            
          </form>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/new/nav.html
{% load static %}
<!-- ================================
Start Navigation Bar
================================= -->


<div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
        </div>
    </div>
    <div class="site-mobile-menu-body"></div>
</div> <!-- .site-mobile-menu -->


<!-- NAVBAR -->
<header class="site-navbar mt-3">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="site-logo col-6"><a href="index.html">JobFinder</a></div>

            <nav class="mx-auto site-navigation">
                <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
                    
                    <li><a href="{% url 'users:home' %}" class="nav-link active">Home</a></li>
                    
                    <li><a href="#">About</a></li>

                    <li><a href="#">Contact</a></li>
                
                {% if is_logged_in %}    
                    {% if is_employer %}
                        <li><a href="{% url 'users:employer_job_list' %}">My Jobs</a></li>
                    {% else %}
                        <li><a href="{% url 'users:my_applications' %}">My Applications</a></li>
                    {% endif %}
                {% endif %}
                
                
                </ul>
            </nav>

            <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                <div class="ml-auto">
                    {% if is_logged_in %}
                        {% if is_employer %}
                            <a href="{% url 'users:job_post' %}" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span
                            class="mr-2 icon-add"></span>Post a Job</a>  
                        {% endif %}
                        <a href="{% url 'users:logout' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span
                        class="mr-2 icon-lock_outline"></span>Log Out</a>
                        
                    {% else %}
                        <a href="{% url 'users:applicant_login' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span
                        class="mr-2 icon-lock_outline"></span>Log In</a>
                        <a href="{% url 'users:applicant_register' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span
                            class="mr-2 icon-lock_outline"></span>Sign Up</a>
                    {% endif %}

                </div>
                <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span
                        class="icon-menu h3 m-0 p-0 mt-2"></span></a>
            </div>

        </div>
    </div>
</header>
<!-- ================================
End Navigation Bar
================================= -->

templates/new/view_applicants.html
{% extends 'new/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section class="section-hero overlay inner-page bg-image" id="home-section">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1 class="text-white font-weight-bold">Job Applications for</h1>
                <h1 class="text-white font-weight-bold">"{{ job.job_title }}"</h1>
                <div class="custom-breadcrumbs">
                    <a href="{% url 'users:home' %}">Home</a> <span class="mx-2 slash">/</span>
                    <span class="text-white"><strong>job applications</strong></span>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="site-section">
    <div class="container-xxl"  >
        {% if job_applicants %}
        <div class="row mb-5 justify-content-center">
            <div class="col-md-7 text-center">
                <h2 class="section-title mb-2">Applicants</h2>
            </div>
        </div>
        <div class="container d-flex justify-content-center mt-4" style="width:100%">

            <table class="table align-middle table-bordered border-secondary">
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col" style="width: 2%;">Sr No</th>
                        <th scope="col" style="width: 15%;">Full Name</th>
                        <th scope="col" style="width: 20%;">Email</th>
                        <th scope="col" style="width: 5%;">Gender</th>
                        <th scope="col" style="width: 15%;">Phone no</th>
                        <th scope="col" style="width: 15%;">Resume</th>
                        <th scope="col" style="width: 15%;">Address</th>
                        <th scope="col" style="width: 20%;">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for application in job_applicants %}
                    <tr class="text-center">
                        <td>{{forloop.counter}}</td>
                        <td>{{ application.first_name }}
                            {{ application.last_name }}</td>
                        <td>{{ application.email }}</td>
                        <td>{{ application.gender }}</td>
                        <td>{{ application.phone_no }}</td>
                        <td><a href="{{ application.resume.url }}">Download Resume</a></td>
                        <td>{{ applicant.address }}</td>
                        <td>
                            <a href="{% url 'users:application_detail' application.id %}" class="btn btn-outline-primary">View</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <div class="row mb-5 justify-content-center">
            <div class="col-md-7 text-center">
                <h2 class="section-title mb-2">No Applications Yet</h2>
            </div>
        </div>
        {% endif %}
    </div>
</section>

{% endblock %}